[tool.poetry]
name = "fight_arena"
version = "0.1.0"
description = "Descripci√≥n de tu proyecto"
authors = ["Tu Nombre <tu@email.com>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
